spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/disbet_db?characterEncoding=utf8
    username: root
    password: root

mybatis:
  config-location: /mapper/*.xml